export interface ServiceData {
  slug: string
  title: string
  category: string
  categorySlug: string
  description: string
  longDescription: string
  image: string
  icon: string
  features: string[]
  benefits: string[]
  process: string[]
}

export const allServices: ServiceData[] = [
  // Residential Cleaning
  {
    slug: "standard-house-cleaning",
    title: "Standard House Cleaning",
    category: "Residential Cleaning",
    categorySlug: "residential-cleaning",
    description: "Scheduled weekly, fortnightly, or monthly cleaning to keep your home consistently maintained without disrupting your routine.",
    longDescription: "Our standard house cleaning service is designed to maintain a consistently clean and comfortable home. Whether you need us weekly, fortnightly, or monthly, our trained team handles all the essentials: dusting, vacuuming, mopping, bathroom sanitisation, and kitchen cleaning. We use eco-friendly products that are safe for your family and pets while delivering a thorough, professional result every time. Serving homes across Johannesburg including Sandton, Randburg, Fourways, Midrand, Bryanston, and Johannesburg North.",
    image: "/house cleaning/house hero.webp",
    icon: "Home",
    features: [
      "Dusting all reachable surfaces",
      "Vacuuming and mopping throughout",
      "Bathrooms cleaned and disinfected",
      "Kitchen counters, sink, and stovetop",
      "Beds made and linens changed",
      "Bins emptied and liners replaced",
      "Mirrors and glass wiped",
      "General tidying of living areas",
    ],
    benefits: [
      "Flexible scheduling: weekly, fortnightly, or monthly",
      "Familiar professionals assigned to your home each visit",
      "Eco-friendly cleaning products used",
      "No lock-in contracts",
      "Loyalty rewards for repeat bookings",
    ],
    process: [
      "We start with a walkthrough to understand your priorities.",
      "Common areas are dusted, vacuumed, and mopped.",
      "Bathrooms are scrubbed, disinfected, and polished.",
      "The kitchen is cleaned: counters, sink, stovetop, and appliance exteriors.",
      "Bedrooms are tidied, beds made, and floors cleaned.",
      "A final check ensures nothing is missed before we leave.",
    ],
  },
  {
    slug: "deep-cleaning",
    title: "Deep Cleaning",
    category: "Residential Cleaning",
    categorySlug: "residential-cleaning",
    description: "A comprehensive clean covering every surface, appliance interior, and hard-to-reach area, well beyond the scope of a standard clean.",
    longDescription: "Our deep cleaning service goes far beyond a standard clean. We tackle built-up grime, hidden dirt, and neglected areas that regular cleaning misses. From inside ovens and fridges to baseboards, light fixtures, and behind furniture, every corner of your home receives thorough attention. Ideal for seasonal refreshes, pre-event preparation, or when your home requires a higher level of clean. Available across Johannesburg and surrounding areas.",
    image: "/deep cleaning/deep clean.webp",
    icon: "Sparkles",
    features: [
      "All surfaces scrubbed and sanitised",
      "Inside ovens, fridges, and microwaves",
      "Baseboards, skirting boards, and cornices",
      "Window sills and tracks",
      "Light fixtures and ceiling fans",
      "Behind and under furniture",
      "Tile grout deep cleaned",
      "Cabinet interiors wiped down",
    ],
    benefits: [
      "Perfect for seasonal or one-time deep refreshes",
      "Removes built-up grime and allergens",
      "Professional-grade equipment and products",
      "Ideal before or after events",
      "Can be combined with regular cleaning plans",
    ],
    process: [
      "We assess your home and identify high-priority areas.",
      "All surfaces are scrubbed top to bottom: walls, ceilings, and baseboards.",
      "Appliance interiors (oven, fridge, microwave) are thoroughly cleaned.",
      "Bathrooms receive intensive descaling and grout cleaning.",
      "Floors are deep-cleaned including under and behind furniture.",
      "A detailed walkthrough confirms every area meets our standards.",
    ],
  },
  {
    slug: "move-in-move-out-cleaning",
    title: "Move-in / Move-out Cleaning",
    category: "Residential Cleaning",
    categorySlug: "residential-cleaning",
    description: "Whether handing back keys or moving into a new property, we ensure every room and surface meets a thorough handover standard.",
    longDescription: "Moving is demanding enough without the added pressure of cleaning. Our move-in/move-out cleaning service ensures the property is spotless from floor to ceiling, whether you are preparing to hand back keys or want to start fresh in your new home. We clean every cupboard, appliance, and surface so you can focus on the move itself. Trusted by tenants, landlords, and estate agents across Johannesburg.",
    image: "/move in move out/move in move out hero.webp",
    icon: "Truck",
    features: [
      "Full property deep clean",
      "All cupboards and wardrobes wiped out",
      "Appliances cleaned inside and out",
      "Interior window cleaning",
      "Light switches and plug covers sanitised",
      "Door frames and handles cleaned",
      "Garage sweep (where applicable)",
      "Final walkthrough before handover",
    ],
    benefits: [
      "Helps secure your full deposit return",
      "Move into a fresh, hygienic space",
      "Trusted by landlords and estate agents",
      "Available at short notice",
      "Covers every room and surface",
    ],
    process: [
      "We do a full property assessment on arrival.",
      "Every room is cleaned top to bottom: cupboards, walls, and floors.",
      "Kitchen appliances are deep cleaned inside and out.",
      "Bathrooms are fully descaled and sanitised.",
      "Windows, light switches, and door handles are wiped down.",
      "A final walkthrough ensures the property is handover-ready.",
    ],
  },

  // Commercial Cleaning
  {
    slug: "office-cleaning",
    title: "Office Cleaning",
    category: "Commercial Cleaning",
    categorySlug: "commercial-cleaning",
    description: "Professional office cleaning for businesses of all sizes. A clean, well-maintained workplace keeps your team healthy and clients impressed.",
    longDescription: "Professional Office Cleaning Services in Johannesburg. A clean, well-maintained office not only creates a positive first impression for clients but also boosts team morale and supports a healthier work environment. Serving businesses across Johannesburg, Sandton, Randburg, Fourways, Midrand, and Bryanston with owner-supervised, vetted teams and no lock-in contracts.",
    image: "/cleaning images/zenako-office-cleaning-johannesburg.webp",
    icon: "Building2",
    features: [
      "Daily or weekly cleaning schedules",
      "Workstations and equipment sanitised",
      "Reception and meeting rooms maintained",
      "Restrooms and kitchens fully sanitised",
      "Waste removal and recycling sorted",
      "Floor care (carpet, tile, wood)",
      "Vetted and familiar professionals",
      "No lock-in contracts ever",
    ],
    benefits: [
      "Healthier work environment for employees",
      "Professional first impression for visitors",
      "Direct owner supervision and accountability",
      "Familiar professionals assigned each visit",
      "Boosted team morale and productivity",
    ],
    process: [
      "We conduct an initial site visit to assess your needs.",
      "A tailored plan is created for your specific schedule.",
      "Our vetted team cleans workstations and common areas.",
      "Kitchens and restrooms are deep cleaned and sanitised.",
      "A final check ensure standards are met every time.",
    ],
  },
  {
    slug: "small-business-cleaning",
    title: "Small Business Cleaning",
    category: "Commercial Cleaning",
    categorySlug: "commercial-cleaning",
    description: "Affordable cleaning solutions for small businesses, retail shops, and commercial spaces.",
    longDescription: "Small businesses deserve the same level of professional cleaning as large corporations, without the premium price. Our small business cleaning service is tailored to shops, salons, clinics, studios, and other small commercial spaces. We work around your schedule to keep your business looking its best for customers and staff. Affordable packages available across Johannesburg.",
    image: "/cleaning images/zenako-airbnb-cleaning-johannesburg.webp",
    icon: "Building2",
    features: [
      "Tailored to your business type and size",
      "Shop floor and display area cleaning",
      "Restroom and staff area maintenance",
      "Window and entrance cleaning",
      "Waste removal and bin management",
      "Surface disinfection",
      "Flexible day or after-hours scheduling",
      "Monthly or weekly plans available",
    ],
    benefits: [
      "Affordable packages for small businesses",
      "Keeps your space presentable for customers",
      "No long-term contracts required",
      "Customised to your specific industry",
      "Reliable, consistent service",
    ],
    process: [
      "We visit your premises to understand your specific requirements.",
      "A tailored cleaning plan and quote are provided.",
      "Cleaning is scheduled around your business operations.",
      "All customer-facing areas are prioritised.",
      "Back-of-house areas including staff rooms are maintained.",
      "Regular reviews ensure the service meets your evolving needs.",
    ],
  },

  // Upholstery & Fabric Cleaning
  {
    slug: "sofa-cleaning",
    title: "Sofa Cleaning",
    category: "Upholstery & Fabric Cleaning",
    categorySlug: "upholstery-and-fabric",
    description: "Deep cleaning for all types of sofas and couches. We remove stains, dust mites, and odours.",
    longDescription: "Your sofa is one of the most-used pieces of furniture in your home, and it collects dust, allergens, spills, and odours over time. Our professional sofa cleaning service uses safe, effective methods to deep clean all fabric and leather types, removing stains, dust mites, bacteria, and unpleasant smells. Your sofa will look refreshed and feel hygienic. Available across Johannesburg and surrounding areas.",
    image: "/cleaning images/zenako-cleaning-team-walking.webp",
    icon: "Sofa",
    features: [
      "Deep extraction cleaning for all fabric types",
      "Stain and spot treatment",
      "Dust mite and allergen removal",
      "Odour elimination",
      "Leather sofa conditioning",
      "Quick-dry techniques",
      "Safe for pets and children",
      "On-site service at your home",
    ],
    benefits: [
      "Extends the lifespan of your sofa",
      "Removes hidden allergens and bacteria",
      "Restores colour and freshness",
      "No need to transport furniture",
      "Eco-friendly cleaning solutions",
    ],
    process: [
      "We inspect the fabric type and identify any stains or damage.",
      "Pre-treatment is applied to tough stains and high-traffic areas.",
      "Deep extraction cleaning removes dirt, dust mites, and allergens.",
      "Odour neutralising treatment is applied.",
      "The sofa is left to dry with quick-dry techniques.",
      "A final inspection ensures the result meets our standards.",
    ],
  },
  {
    slug: "mattress-cleaning",
    title: "Mattress Cleaning",
    category: "Upholstery & Fabric Cleaning",
    categorySlug: "upholstery-and-fabric",
    description: "Professional mattress sanitisation to remove allergens, dust mites, and bacteria.",
    longDescription: "You spend a third of your life on your mattress, so it should be clean and hygienic. Our professional mattress cleaning service removes dust mites, dead skin cells, bacteria, sweat stains, and allergens that build up over time. Using safe, chemical-free methods, we sanitise and freshen your mattress for a healthier night's sleep. Serving homes across Johannesburg.",
    image: "/cleaning images/zenako-cleaning-team-walking.webp",
    icon: "Sofa",
    features: [
      "Deep dust mite extraction",
      "Allergen and bacteria removal",
      "Sweat and stain treatment",
      "UV sanitisation available",
      "Odour elimination",
      "Safe, chemical-free methods",
      "All mattress sizes catered for",
      "On-site service",
    ],
    benefits: [
      "Improved sleep quality",
      "Reduces allergy and asthma triggers",
      "Extends mattress lifespan",
      "Chemical-free and family safe",
      "Quick-dry results, ready to use the same night",
    ],
    process: [
      "The mattress is inspected for stains and problem areas.",
      "High-powered vacuuming removes surface dust and debris.",
      "Deep extraction cleaning targets embedded dirt and allergens.",
      "Stains are treated with specialised solutions.",
      "Sanitisation eliminates bacteria and dust mites.",
      "The mattress is left fresh and ready for use.",
    ],
  },
  {
    slug: "curtain-cleaning",
    title: "Curtain Cleaning",
    category: "Upholstery & Fabric Cleaning",
    categorySlug: "upholstery-and-fabric",
    description: "Professional on-site curtain cleaning in Johannesburg. We clean most curtains while they remain hanging, removing dust, allergens, and odours without the hassle of removal.",
    longDescription: "Curtains act as filters for dust, pollen, and allergens. Over time, these particles settle into the fabric, which can lead to discoloration and affect indoor air quality. Zenako Cleaning Co. provides specialised on-site curtain cleaning across Johannesburg to restore your window treatments without the need for removal. We clean most curtains while they are still hanging on the rail, using controlled steam extraction to lift dust and grime from the fibres while targeting dust mites, household odours, and allergens. Our method is designed to prevent shrinkage and maintain the original length and texture of your drapes.",
    image: "/Curtain-Cleaning.jpg",
    icon: "Wind",
    features: [
      "On-site cleaning — no removal or re-hanging needed",
      "Steam extraction to lift dust and grime from fibres",
      "Sanitisation targeting dust mites and household odours",
      "Fabric integrity care to prevent shrinkage",
      "Heavy drapes and velvet deep cleaning",
      "Gentle vacuuming and light steaming for sheers and lace",
      "Specialised cleaning for blackout curtain linings",
      "Targeted treatment for Roman blinds and fabric vertical blinds",
    ],
    benefits: [
      "Direct owner supervision — no call centres, direct access to management",
      "100% vetted professionals trained in fabric care",
      "No hidden costs — clear quotes with no price changes after quoting",
      "Gauteng expertise with techniques suited to sun-damaged fabrics",
      "Improves indoor air quality by removing dust, pollen, and allergens",
    ],
    process: [
      "Inspection: We check for fabric stability and potential sun damage.",
      "Vacuuming: High-power vacuuming to remove surface dust and cobwebs.",
      "Spot Treatment: Targeted cleaning for specific stains or water marks.",
      "Steam Extraction: Deep-cleaning the fibres while the curtains remain hanging.",
      "Deodorizing: A final treatment to leave the room fresh.",
    ],
  },
  {
    slug: "carpet-cleaning",
    title: "Carpet Cleaning",
    category: "Upholstery & Fabric Cleaning",
    categorySlug: "upholstery-and-fabric",
    description: "Expert carpet cleaning that removes deep stains, allergens, and odours.",
    longDescription: "Carpets trap dirt, dust, allergens, pet dander, and spills deep in their fibres, well beyond what regular vacuuming can reach. Our professional carpet cleaning service uses hot water extraction and eco-friendly solutions to deep clean your carpets, removing stubborn stains and odours while restoring colour and texture. Serving homes and offices across Johannesburg.",
    image: "/cleaning images/Deep Carpet cleaning image 1.webp",
    icon: "Sparkles",
    features: [
      "Hot water extraction deep cleaning",
      "Stubborn stain removal",
      "Pet stain and odour treatment",
      "Allergen and dust mite elimination",
      "Colour and texture restoration",
      "Quick-dry technology",
      "Safe for all carpet types",
      "Commercial and residential service",
    ],
    benefits: [
      "Removes 98% of allergens and bacteria",
      "Extends carpet lifespan significantly",
      "Restores original colour and softness",
      "Safe for children and pets",
      "Dries within hours, not days",
    ],
    process: [
      "We inspect the carpet for stains, damage, and fibre type.",
      "Pre-treatment solution is applied to high-traffic and stained areas.",
      "Hot water extraction deep cleans the entire carpet.",
      "Stubborn stains receive targeted treatment.",
      "Deodoriser is applied to eliminate lingering odours.",
      "Quick-dry fans speed up drying time.",
    ],
  },
  {
    slug: "upholstery-furniture-cleaning",
    title: "Upholstery Cleaning",
    category: "Upholstery & Fabric Cleaning",
    categorySlug: "upholstery-and-fabric",
    description: "Comprehensive cleaning for chairs, ottomans, cushions, and other upholstered furniture.",
    longDescription: "From dining chairs and ottomans to headboards and cushions, upholstered furniture collects dust, stains, and allergens over time. Our professional upholstery cleaning service is safe for all fabric types and effectively removes embedded dirt, bacteria, and odours. We clean on-site at your home or office, so there's no need to move heavy furniture. Available across Johannesburg and surrounding areas.",
    image: "/cleaning images/zenako-cleaning-team.webp",
    icon: "Sofa",
    features: [
      "All upholstered furniture types",
      "Dining chairs and armchairs",
      "Ottomans and footstools",
      "Headboards and cushions",
      "Fabric and leather options",
      "Stain and spot treatment",
      "Allergen removal",
      "On-site cleaning service",
    ],
    benefits: [
      "Refreshes your entire living space",
      "Removes hidden allergens and bacteria",
      "Extends furniture lifespan",
      "Convenient on-site service",
      "Multi-piece discounts available",
    ],
    process: [
      "Each piece is inspected for fabric type and staining.",
      "Pre-treatment is applied to soiled and stained areas.",
      "Deep extraction cleaning removes embedded dirt and allergens.",
      "Stains are individually treated for best results.",
      "Fabric protector can be applied on request.",
      "Furniture is left clean, fresh, and ready to use.",
    ],
  },

  // Specialised Cleaning Services
  {
    slug: "roof-cleaning",
    title: "Roof Cleaning",
    category: "Specialised Cleaning Services",
    categorySlug: "specialised-cleaning",
    description: "Professional roof cleaning to remove moss, algae, and built-up dirt.",
    longDescription: "Over time, roofs accumulate moss, algae, lichen, and general grime that not only looks unsightly but can cause structural damage if left untreated. Our professional roof cleaning service safely removes all build-up, restoring your roof's appearance and extending its lifespan. We use appropriate methods for tile, metal, and other roofing materials. Serving properties across Johannesburg.",
    image: "/cleaning images/zenako-roof-cleaning.webp",
    icon: "Home",
    features: [
      "Moss and algae removal",
      "Lichen treatment",
      "Gutter cleaning included",
      "Tile and metal roof cleaning",
      "Pressure washing where appropriate",
      "Preventative treatment application",
      "Safety-compliant methods",
      "Before and after documentation",
    ],
    benefits: [
      "Improves curb appeal and property value",
      "Prevents long-term roof damage",
      "Extends roof lifespan",
      "Reduces risk of leaks",
      "Professional, accountable team",
    ],
    process: [
      "We assess your roof type and condition from the ground.",
      "Safety equipment is set up for safe access.",
      "Loose debris, moss, and algae are carefully removed.",
      "The roof is pressure-washed or soft-washed as appropriate.",
      "Gutters are cleared of debris.",
      "A preventative treatment is applied to inhibit regrowth.",
    ],
  },
  {
    slug: "drain-cleaning",
    title: "Drain Cleaning",
    category: "Specialised Cleaning Services",
    categorySlug: "specialised-cleaning",
    description: "Fast, reliable drain cleaning and unblocking in Johannesburg. We resolve blocked toilets, overflowing sinks, and sewer line backups with owner-supervised, vetted teams.",
    longDescription: "Professional Drain Cleaning & Unblocking in Johannesburg. If your drains are slow, smells are emerging, or your bathroom and kitchen fixtures are overflowing, professional cleaning is required. Zenako Cleaning Co. specialises in clearing blocked toilets and main sewer lines, slow-draining showers, baths, and basins, kitchen sink blockages and grease build-up, and sewer backups and septic tank issues. We use professional-grade electro-mechanical cleaning, high-pressure water jetting, and CCTV camera inspections to deliver long-lasting results across Johannesburg and surrounding areas.",
    image: "/cleaning-kitchen-sink-drain.webp",
    icon: "Droplets",
    features: [
      "Blocked toilet and main sewer line clearing",
      "Slow-draining showers, baths, and basins",
      "Kitchen sink blockages and grease build-up",
      "Sewer backups and septic tank issues",
      "Electro-mechanical cleaning for stubborn blockages",
      "High-pressure water jetting to remove grease and scale",
      "CCTV camera inspections for broken or recurring issues",
      "On-site quote before any work begins",
    ],
    benefits: [
      "Direct owner supervision — no call centres, direct access to management",
      "Vetted professionals background-checked and trained for complex drainage repairs",
      "No price changes — the quoted price is the price you pay",
      "7-day service for urgent overflows and blockages",
      "Fast, clean, and reliable resolution, often on the same day",
    ],
    process: [
      "Assessment: A technician arrives to assess the blockage and determine the root cause.",
      "Instant Quote: You receive a clear, no-obligation quote on-site before any work begins.",
      "On-Site Resolution: Once approved, we carry out the unblocking, often on the same day.",
      "Final Inspection: We ensure the lines are clear and behaving correctly before we leave the site.",
    ],
  },
  {
    slug: "garden-clean-ups",
    title: "Garden Clean-ups",
    category: "Specialised Cleaning Services",
    categorySlug: "specialised-cleaning",
    description: "Tidy up your outdoor spaces with clearing, trimming, and general maintenance.",
    longDescription: "An overgrown or untidy garden can significantly affect the appearance of your property. Our garden clean-up service covers everything from clearing debris and trimming overgrowth to general tidying and waste removal, whether for a one-time restoration or regular ongoing maintenance. Available across Johannesburg and surrounding areas.",
    image: "/cleaning images/zenako-garden-cleaning.webp",
    icon: "TreePine",
    features: [
      "Overgrowth clearing and trimming",
      "Lawn mowing and edging",
      "Hedge and shrub trimming",
      "Garden debris removal",
      "Leaf clearing and composting",
      "Weed removal",
      "Pathway and patio cleaning",
      "Green waste disposal",
    ],
    benefits: [
      "Instantly improves property appearance",
      "Reduces pest harbourage areas",
      "Prepares gardens for landscaping",
      "One-time or regular service available",
      "All waste removed from premises",
    ],
    process: [
      "We survey the garden and discuss your goals.",
      "Overgrown areas are cleared and trimmed back.",
      "Lawns are mowed and edges neatened.",
      "Debris, weeds, and fallen branches are removed.",
      "Pathways and patios are swept or pressure-washed.",
      "All green waste is removed from the property.",
    ],
  },
  {
    slug: "pest-control",
    title: "Pest Control",
    category: "Specialised Cleaning Services",
    categorySlug: "specialised-cleaning",
    description: "Targeted pest treatments using eco-friendly products safe for your family and pets.",
    longDescription: "Pests can cause health risks, property damage, and general discomfort. Our pest control service uses targeted, eco-friendly treatments to eliminate pests at the source, addressing the root cause rather than the surface. We treat ants, cockroaches, rodents, spiders, bed bugs, mosquitoes, and more. All products are safe for families and pets. We also offer ongoing prevention plans to keep your home pest-free. Serving Johannesburg and surrounding areas.",
    image: "/cleaning images/zenako-disinfection-fogging-johannesburg.webp",
    icon: "Bug",
    features: [
      "Full property pest inspection",
      "Ant and cockroach treatment",
      "Spider control",
      "Rodent prevention and sealing",
      "Bed bug treatment",
      "Mosquito spraying",
      "Eco-friendly, low-toxicity products",
      "Ongoing prevention plans",
    ],
    benefits: [
      "Safe for children and pets",
      "Targets pests at the source",
      "Prevents reinfestation",
      "Discreet, professional service",
      "Ongoing monitoring available",
    ],
    process: [
      "We conduct a full property inspection to identify pest activity.",
      "The type and extent of infestation is assessed.",
      "A targeted treatment plan is created.",
      "Safe, eco-friendly products are applied to affected areas.",
      "Entry points are sealed where possible.",
      "Follow-up visits are scheduled to ensure full elimination.",
    ],
  },
  {
    slug: "disinfection-services",
    title: "Disinfection Services",
    category: "Specialised Cleaning Services",
    categorySlug: "specialised-cleaning",
    description: "Thorough disinfection and sanitisation for homes and businesses.",
    longDescription: "Protect your family, employees, and customers with our professional disinfection service. We provide thorough sanitisation of all surfaces using hospital-grade, eco-friendly disinfectants that eliminate bacteria, viruses, and germs. Ideal for homes, offices, schools, clinics, and any space that needs a higher level of hygiene. Available across Johannesburg and surrounding areas.",
    image: "/cleaning images/zenako-disinfection-fogging-johannesburg.webp",
    icon: "ShieldCheck",
    features: [
      "Full-premises disinfection",
      "Hospital-grade sanitising products",
      "High-touch surface focus",
      "Fogging and spray application",
      "Air purification treatment",
      "Safe for all surface types",
      "Rapid drying formula",
      "Certificate of disinfection provided",
    ],
    benefits: [
      "Eliminates 99.9% of bacteria and viruses",
      "Creates a safer environment for all",
      "Meets health and safety compliance",
      "Minimal disruption to daily operations",
      "Peace of mind for staff and visitors",
    ],
    process: [
      "We assess the premises and identify high-risk areas.",
      "All high-touch surfaces are pre-cleaned.",
      "Hospital-grade disinfectant is applied via spray or fogging.",
      "Air purification treatment is applied if needed.",
      "The space is ventilated and dried.",
      "A disinfection certificate is provided on request.",
    ],
  },
]

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return allServices.find((s) => s.slug === slug)
}

export function getRelatedServices(slug: string, limit = 3): ServiceData[] {
  const current = getServiceBySlug(slug)
  if (!current) return allServices.slice(0, limit)

  // First try same category, then fill with others
  const sameCategory = allServices.filter(
    (s) => s.categorySlug === current.categorySlug && s.slug !== slug
  )
  const others = allServices.filter(
    (s) => s.categorySlug !== current.categorySlug && s.slug !== slug
  )
  return [...sameCategory, ...others].slice(0, limit)
}

export const serviceCategories = [
  {
    name: "Residential Cleaning",
    slug: "residential-cleaning",
    services: [
      { name: "Standard House Cleaning", slug: "standard-house-cleaning" },
      { name: "Deep Cleaning", slug: "deep-cleaning" },
      { name: "Move-in/Move-out Cleaning", slug: "move-in-move-out-cleaning" },
    ],
  },
  {
    name: "Commercial Cleaning",
    slug: "commercial-cleaning",
    services: [
      { name: "Office Cleaning", slug: "office-cleaning" },
      { name: "Small Business Cleaning", slug: "small-business-cleaning" },
    ],
  },
  {
    name: "Upholstery & Fabric",
    slug: "upholstery-and-fabric",
    services: [
      { name: "Sofa Cleaning", slug: "sofa-cleaning" },
      { name: "Mattress Cleaning", slug: "mattress-cleaning" },
      { name: "Curtain Cleaning", slug: "curtain-cleaning" },
      { name: "Carpet Cleaning", slug: "carpet-cleaning" },
      { name: "Upholstery Cleaning", slug: "upholstery-furniture-cleaning" },
    ],
  },
  {
    name: "Specialised Services",
    slug: "specialised-cleaning",
    services: [
      { name: "Roof Cleaning", slug: "roof-cleaning" },
      { name: "Drain Cleaning", slug: "drain-cleaning" },
      { name: "Garden Clean-ups", slug: "garden-clean-ups" },
      { name: "Pest Control", slug: "pest-control" },
      { name: "Disinfection Services", slug: "disinfection-services" },
    ],
  },
]
